import type { EnemyDef } from "../core/content-types";

/** Tuned with the balance bots (tests/balance.test.ts); run `npm run balance` after changing. */
export const ENEMIES: readonly EnemyDef[] = [
  {
    id: "runner",
    name: "Runner",
    hp: 21,
    speed: 2.4,
    armor: 0,
    bounty: 6,
    leakDamage: 1,
    radius: 0.22,
  },
  {
    id: "grunt",
    name: "Grunt",
    hp: 45,
    speed: 1.4,
    armor: 1,
    bounty: 9,
    leakDamage: 1,
    radius: 0.28,
  },
  {
    id: "brute",
    name: "Brute",
    hp: 165,
    speed: 0.9,
    armor: 4,
    bounty: 23,
    leakDamage: 3,
    radius: 0.36,
  },
  {
    id: "warden",
    name: "Warden",
    hp: 900,
    speed: 0.7,
    armor: 6,
    bounty: 225,
    leakDamage: 20,
    radius: 0.45,
  },
  {
    id: "wisp",
    name: "Wisp",
    hp: 30,
    speed: 1.6,
    armor: 0,
    bounty: 7,
    leakDamage: 1,
    radius: 0.24,
    flying: true,
  },
  {
    id: "mender",
    name: "Mender",
    hp: 75,
    speed: 1.2,
    armor: 2,
    bounty: 14,
    leakDamage: 2,
    radius: 0.3,
    heal: { amount: 12, radius: 1.8, interval: 2 },
  },
  {
    id: "harrier",
    name: "Harrier",
    hp: 100,
    speed: 1.2,
    armor: 2,
    bounty: 16,
    leakDamage: 2,
    radius: 0.32,
    flying: true,
  },
  {
    id: "brood",
    name: "Brood",
    hp: 90,
    speed: 1.1,
    armor: 1,
    bounty: 10,
    leakDamage: 2,
    radius: 0.34,
    split: { enemy: "broodling", count: 3 },
  },
  {
    id: "broodling",
    name: "Broodling",
    hp: 16,
    speed: 2,
    armor: 0,
    bounty: 2,
    leakDamage: 1,
    radius: 0.18,
  },
  {
    id: "tyrant",
    name: "Rift Tyrant",
    hp: 2600,
    speed: 0.55,
    armor: 8,
    bounty: 500,
    leakDamage: 20,
    radius: 0.5,
    split: { enemy: "brute", count: 4 },
  },
];
